-   id: check-rebase
    name: Check if rebase is needed
    description: Check if your branch is up to date with the upstream.
    entry: ./pre-commit-hooks/check-rebase.py
    language: script
    always_run: true
    args: [upstream_url]

-   id: validate-config
    name: Validate package config
    description: Check for missing values and incorrect types
    entry: ./pre-commit-hooks/validate-config.sh
    language: script
    files: ^\.?packit.ya?ml$

-   id: validate-config-in-container
    name: Validate package config
    description: Check for missing values and incorrect types
    entry: quay.io/packit/packit:latest packit -d config validate
    language: docker_image
    files: ^\.?packit.ya?ml$
